### ISSUE TITLE
Install failure with SyntaxError

### ISSUE THREAD

**Issue by kelemeng** [allotropia/gtimelog#3]
When trying to run "sudo ./setup.py install" after ./setup.py build on Ubuntu 20.04 it fails with:

gabor@shuttle:~/thinclient_drives/gtimelog$ sudo ./setup.py install
running install
running bdist_egg
running egg_info
writing src/gtimelog.egg-info/PKG-INFO
writing dependency_links to src/gtimelog.egg-info/dependency_links.txt
writing entry points to src/gtimelog.egg-info/entry_points.txt
writing requirements to src/gtimelog.egg-info/requires.txt
writing top-level names to src/gtimelog.egg-info/top_level.txt
reading manifest file 'src/gtimelog.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst'
warning: no files found matching 'Makefile'
warning: no files found matching '*.mk'
warning: no files found matching 'gtimelog.desktop.in'
warning: no files found matching 'gtimelog.appdata.xml'
warning: no files found matching 'tox.ini'
warning: no files found matching 'appveyor.yml'
warning: no files found matching '.travis.yml'
warning: no files found matching '.coveragerc'
warning: no files found matching '.gitattributes'
warning: no files found matching 'benchmark.py'
warning: no files found matching '*.xml' under directory 'src'
warning: no files found matching '*.css' under directory 'src'
warning: no files found matching '*.rst' under directory 'src'
warning: no files found matching 'gschemas.compiled' under directory 'src'
warning: no files found matching '*.png' under directory 'docs'
warning: no files found matching '*.rst' under directory 'docs'
warning: no files found matching '*.css' under directory 'docs'
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching '*.py' under directory 'scripts'
warning: no files found matching '*.rst' under directory 'scripts'
warning: no files found matching '*.po' under directory 'src/gtimelog/po'
warning: no files found matching '*.pot' under directory 'src/gtimelog/po'
warning: no files found matching '*.in' under directory 'src/gtimelog/po'
warning: no files found matching '*.yaml' under directory 'flatpak'
no previously-included directories found matching 'docs/build'
writing manifest file 'src/gtimelog.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/paths.py -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/tzoffset.py -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/__init__.py -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/gtimelog.ui -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/gtimelog.png -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/secrets.py -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/settings.py -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/rltimelog.py -> build/bdist.linux-x86_64/egg/gtimelog
creating build/bdist.linux-x86_64/egg/gtimelog/tests
copying build/lib/gtimelog/tests/__init__.py -> build/bdist.linux-x86_64/egg/gtimelog/tests
copying build/lib/gtimelog/tests/test_timelog.py -> build/bdist.linux-x86_64/egg/gtimelog/tests
copying build/lib/gtimelog/tests/__main__.py -> build/bdist.linux-x86_64/egg/gtimelog/tests
copying build/lib/gtimelog/utils.py -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/timelog.py -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/main.py -> build/bdist.linux-x86_64/egg/gtimelog
copying build/lib/gtimelog/allotropia.py -> build/bdist.linux-x86_64/egg/gtimelog
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/paths.py to paths.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/tzoffset.py to tzoffset.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/secrets.py to secrets.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/settings.py to settings.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/rltimelog.py to rltimelog.cpython-38.pyc
  File "build/bdist.linux-x86_64/egg/gtimelog/rltimelog.py", line 125
    message.request_body.append(json.dumps(data, indent='\t')).encode())
                                                                       ^
SyntaxError: unmatched ')'

byte-compiling build/bdist.linux-x86_64/egg/gtimelog/tests/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/tests/test_timelog.py to test_timelog.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/tests/__main__.py to __main__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/utils.py to utils.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/timelog.py to timelog.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/main.py to main.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/gtimelog/allotropia.py to allotropia.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/gtimelog.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/gtimelog.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/gtimelog.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/gtimelog.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/gtimelog.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/gtimelog.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/gtimelog.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/gtimelog-0.2.3-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing gtimelog-0.2.3-py3.8.egg
creating /usr/local/lib/python3.8/dist-packages/gtimelog-0.2.3-py3.8.egg
Extracting gtimelog-0.2.3-py3.8.egg to /usr/local/lib/python3.8/dist-packages
  File "/usr/local/lib/python3.8/dist-packages/gtimelog-0.2.3-py3.8.egg/gtimelog/rltimelog.py", line 125
    message.request_body.append(json.dumps(data, indent='\t')).encode())
                                                                       ^
SyntaxError: unmatched ')'

Adding gtimelog 0.2.3 to easy-install.pth file
Installing rltimelog script to /usr/local/bin
Installing gtimelog script to /usr/local/bin

Installed /usr/local/lib/python3.8/dist-packages/gtimelog-0.2.3-py3.8.egg
Processing dependencies for gtimelog==0.2.3
Searching for PyGObject==3.36.0
Best match: PyGObject 3.36.0
Adding PyGObject 3.36.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for pycairo==1.16.2
Best match: pycairo 1.16.2
Adding pycairo 1.16.2 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for gtimelog==0.2.3

**Comment by thorstenb** [comment]
checked against current main branch HEAD:

~~~
        distrobox enter --root ubuntu_focal-fossa -- /bin/bash
        sudo apt install python3
        sudo apt install python3-setuptools
        sudo apt install libglib2.0-dev
        sudo apt install gobject-introspection
        sudo apt install python3-gi
        sudo apt install python3-gi-cairo
        sudo ./setup.py  install
~~~

Setup then passing w/o error.
